### ISSUE TITLE
cannot connect to selenium chrome container 

### ISSUE THREAD

**Issue by StrangeKarma** [alexschwantes/testcafe-browser-provider-selenium#4]
Hello Alex,
I'm having trouble connecting to the chrome container using the 0.3.0 version of  testcafe-browser-provider-selenium. I supplied some repo steps below. Please let me know if you need more details.
Thanks.
1. docker-compose.yml

version: '2'
services:
  chrome:
    image: selenium/node-chrome:3.141.59-gold
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - hub
    environment:
      HUB_HOST: hub

  hub:
    image: selenium/hub:3.141.59-gold
    ports:
      - "4444:4444"

2. docker-compose up

3. Connection code:
createTestCafe('localhost', 1338 + iteration, 1339 + iteration)
			.then(function(tc) {
				cafeRunner = tc
				const runner = tc.createRunner()
				return runner
					.src('./test.js')
					.screenshots('./reports/screenshots', true)
					.browsers('selenium:chrome')
					.run()
					.catch(function(error) {
						console.error(error)
					})
			})
			.then(function(report) {})

4. Error Messages: chrome container logs:
2019-02-11 19:34:57,817 INFO Included extra file "/etc/supervisor/conf.d/selenium.conf" during parsing
2019-02-11 19:34:57,819 INFO supervisord started with pid 7
2019-02-11 19:34:58,821 INFO spawned: 'xvfb' with pid 10
2019-02-11 19:34:58,822 INFO spawned: 'selenium-node' with pid 11
Connecting to the Hub using the host hub and port 4444
2019-02-11 19:34:58,865 INFO success: xvfb entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
2019-02-11 19:34:58,865 INFO success: selenium-node entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
19:34:59.064 INFO [GridLauncherV3.parse] - Selenium server version: 3.141.59, revision: e82be7d358
19:34:59.151 INFO [GridLauncherV3.lambda$buildLaunchers$7] - Launching a Selenium Grid node on port 5555
2019-02-11 19:34:59.216:INFO::main: Logging initialized @346ms to org.seleniumhq.jetty9.util.log.StdErrLog
19:34:59.379 INFO [WebDriverServlet.<init>] - Initialising WebDriverServlet
19:34:59.440 INFO [SeleniumServer.boot] - Selenium Server is up and running on port 5555
19:34:59.440 INFO [GridLauncherV3.lambda$buildLaunchers$7] - Selenium Grid node is up and ready to register to the hub
19:34:59.496 INFO [SelfRegisteringRemote$1.run] - Starting auto registration thread. Will try to register every 5000 ms.
19:34:59.777 INFO [SelfRegisteringRemote.registerToHub] - Registering the node to the hub: http://hub:4444/grid/register
19:34:59.830 INFO [SelfRegisteringRemote.registerToHub] - The node is registered to the hub and ready to use
19:36:28.681 INFO [ActiveSessionFactory.apply] - Capabilities are: {
  "browserName": "chrome",
  "goog:chromeOptions": {
  }
}
19:36:28.684 INFO [ActiveSessionFactory.lambda$apply$11] - Matched factory org.openqa.selenium.grid.session.remote.ServicedSession$Factory (provider: org.openqa.selenium.chrome.ChromeDriverService)
Starting ChromeDriver 2.46.628388 (4a34a70827ac54148e092aafb70504c4ea7ae926) on port 17775
Only local connections are allowed.
Please protect ports used by ChromeDriver and related test framew[or1k5s4 9t9o1 3p7r8e8v.e7n1t1 ]a[cScEeVERE]: bind() failed: Csannot assign requested address (99)
s by malicious code.
19:36:29.177 INFO [ProtocolHandshake.createSession] - Detected dialect: OSS
19:36:29.495 INFO [RemoteSession$Factory.lambda$performHandshake$0] - Started new session 530de56c5b29e5db48517cc96b438a96 (org.openqa.selenium.chrome.ChromeDriverService)

5. TestCafe Error message:
Server started on port 3000
{ Error: Unable to establish one or more of the specified browser connections. This can be caused by network issues or remote device failure.
    at BrowserSet._callee4$ (c:\costar-suite-market-search\tests\node_modules\testcafe\lib\runner\browser-set.js:219:44)
    at tryCatch (c:\costar-suite-market-search\tests\node_modules\regenerator-runtime\runtime.js:62:40)
    at Generator.invoke [as _invoke] (c:\costar-suite-market-search\tests\node_modules\regenerator-runtime\runtime.js:296:22)
    at Generator.prototype.(anonymous function) [as next] (c:\costar-suite-market-search\tests\node_modules\regenerator-runtime\runtime.js:114:21)
    at step (c:\costar-suite-market-search\tests\node_modules\babel-runtime\helpers\asyncToGenerator.js:17:30)
    at c:\costar-suite-market-search\tests\node_modules\babel-runtime\helpers\asyncToGenerator.js:35:14
    at new Promise (<anonymous>)
    at new F (c:\costar-suite-market-search\tests\node_modules\core-js\library\modules\_export.js:36:28)
    at BrowserSet.<anonymous> (c:\costar-suite-market-search\tests\node_modules\babel-runtime\helpers\asyncToGenerator.js:14:12)
    at BrowserSet._waitConnectionsOpened (c:\costar-suite-market-search\tests\node_modules\testcafe\lib\runner\browser-set.js:237:26)
    at c:\costar-suite-market-search\tests\node_modules\testcafe\lib\runner\browser-set.js:263:31
    at invokeCallback (c:\costar-suite-market-search\tests\node_modules\pinkie\index.js:60:12)
    at Array.forEach (<anonymous>)
    at publish (c:\costar-suite-market-search\tests\node_modules\pinkie\index.js:147:32)
    at Array.publishFulfillment (c:\costar-suite-market-search\tests\node_modules\pinkie\index.js:152:2)
    at Immediate.asyncFlush [as _onImmediate] (c:\costar-suite-market-search\tests\node_modules\pinkie\index.js:17:19) constructor: [Function: GeneralError] }

**Comment by alexschwantes** [comment]
did you set the `SELENIUM_SERVER` environment variable to be the url to the selenium server? see the readme for example of how url should look.

**Comment by StrangeKarma** [comment]
Hi Alex, i have process.env.SELENIUM_SERVER set in my code to point to the rancher instance we have here onsite.

**Comment by link89** [comment]
You should run with
SELENIUM_SERVER=http://youurl testcafe selenium:chrome yourcase.js
